# Generated by Django 2.2.5 on 2019-09-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='receiver_object_id',
            field=models.BigIntegerField(),
        ),
    ]
